dataset:
    type: "synthetic"
    sources:
        synthetic:
            folder_name: "synthetic/perspective"
            train: 0
            val: 0.5
            test: 0.5
    train:
        mode: "train"
        aug:
            gen_onthefly: True
            num_samples: 2048
        loader_args:
            batch_size: 5
            num_workers: &num_workers 4
            shuffle: True
            drop_last: True
            pin_memory: True
    val:
        mode: "test" ####### Important
        aug:
            gen_onthefly: False
        loader_args:
            batch_size: 4
            num_workers: *num_workers
            shuffle: False
            drop_last: False
            pin_memory: True
    test:
        mode: "test" ####### Important
        aug:
            gen_onthefly: False
        loader_args:
            batch_size: 4
            num_workers: *num_workers
            shuffle: False
            drop_last: False
            pin_memory: True
model:
    name: "magicpoint"
    encoder: "vgg"
    decoder: "magicpoint"
    description_dim: 256
    save_path: "./save"
training:
    n_epochs: 100
    optimizer:
        name: "adam"
        learning_rate: 0.001
    accelerator:
        device: "gpu"
        gpus: 1
    log_every_n_batch: 5
    early_stopping_patience: 50
    pointness_loss_weight: 1000

